version: '2'
services:

  base:
    image: clojure:latest
    volumes:
     - .:/usr/src/app
    working_dir: /usr/src/app

  dev:
    extends: base
    environment:
     - LEIN_SILENT=true
    command: lein run

  build:
    extends: base
    command: lein bin

  lint:
    extends: base
    command: lein eastwood
