version: '2'
services:

  dev:
    image: clojure:latest
    environment:
     - LEIN_SILENT=true
    volumes:
     - .:/usr/src/app
    working_dir: /usr/src/app
    command: lein run

  build:
    image: clojure:latest
    volumes:
     - .:/usr/src/app
    working_dir: /usr/src/app
    command: lein bin

  lint:
    image: clojure:latest
    volumes:
     - .:/usr/src/app
    working_dir: /usr/src/app
    command: lein eastwood
